default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: happy_user
  password: 1
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dollar_rate_dev

test:
  <<: *default
  database: dollar_rate_test

production:
  <<: *default
  database: dollar_rate_prod
